spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092,localhost:9093}
      group-id: ${CONSUMER_GROUP:test_group_id}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
